apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: business-api-ingress
  labels:
    name: business-api-ingress
spec:
  rules:
  - host: api.hypertheory-class.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: business-api-service
            port: 
              number: 80
