name: CI CD Pipeline

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
    paths:
     - 'backend/BusinessSolution/**'


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./backend/BusinessSolution/
    - name: Build
      run: dotnet build --no-restore ./backend/BusinessSolution
    - name: Unit Test
      run: dotnet test ./backend/BusinessSolution/BusinessApi.UnitTests --no-build --verbosity normal
    - name: Integration Test
      run: dotnet test ./backend/BusinessSolution/BusinessApi.IntegrationTests --no-build --verbosity normal
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.5.0
      with:
        images: jeffrygonzalez/business-api-jun-2023
        tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
    - name: Build and Push Docker Images
      uses: docker/build-push-action@v4.1.0
      with:
        context: "{{defaultContext}}:./backend/BusinessSolution"
        file: "BusinessApi/Dockerfile"
        push: true
        tags: ${{steps.meta.outputs.tags }}
        labels: ${{steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max